version: '3.8'
services:
  game:
    #image: 'analytics:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: game
    ports:
      - '8989:8080'
   # volumes:
   #   - /WEB-INF:/home/ubuntu/game/src/main/webapp/WEB-INF/