version: '3.8'
services:
  analytics:
    #image: 'analytics:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: game
    ports:
      - '8989:8080'